coma-team/project-climbing-spring

src/main/java/com/coma/app/view/admin/AdminController.java, src/main/java/com/coma/app/view/annotation/LoginCheck.java, src/main/java/com/coma/app/view/common/FileManager.java, src/main/java/com/coma/app/view/common/ValidFilter.java, src/main/java/com/coma/app/view/function/ProfileUpload.java, src/main/java/com/coma/app/view/gym/CrewBattleApplicationController.java, src/main/java/com/coma/app/view/gym/FavoriteController.java, src/main/java/com/coma/app/view/gym/GymController.java, src/main/java/com/coma/app/view/member/CheckController.java, src/main/java/com/coma/app/view/member/JoinController.java, src/main/java/com/coma/app/view/member/LoginAPIController.java, src/main/java/com/coma/app/view/member/LoginAspect.java, src/main/java/com/coma/app/view/member/LoginCheck.java, src/main/java/com/coma/app/view/member/LoginController.java, src/main/java/com/coma/app/view/mypage/MyPageController.java, src/main/java/com/coma/app/view/ranking/RankingController.java, src/main/java/com/coma/app/view/store/StoreController.java, src/main/resources/applicationContext.xml, src/main/webapp/WEB-INF/ds-servlet.xml
=> 예나 Controller 코드 추가

src/main/java/com/coma/app/biz/gym/GymService.java, src/main/java/com/coma/app/biz/gym/GymServiceImpl.java, src/main/java/com/coma/app/biz/member/MemberService.java, src/main/java/com/coma/app/biz/member/MemberServiceImpl.java, src/main/java/com/coma/app/biz/reply/ReplyService.java, src/main/java/com/coma/app/biz/reservation/ReservationService.java, src/main/java/com/coma/app/biz/reservation/ReservationServiceImpl.java
Service - DAO에 맞춤
ServiceImpl - DAO에 맞춤
=> [코드수정] - 선호 241026 DB

src/main/java/com/coma/app/biz/admin/BoardManagementService.java, src/main/java/com/coma/app/biz/admin/CrewManagementService.java, src/main/java/com/coma/app/biz/admin/GymManagementService.java, src/main/java/com/coma/app/biz/admin/MainManagementService.java, src/main/java/com/coma/app/biz/admin/ReservationManagementService.java, src/main/java/com/coma/app/biz/admin/UserManagementService.java
=> [Service 추가]

pom.xml, src/main/java/com/coma/app/biz/battle/BattleDTO.java, src/main/java/com/coma/app/biz/battle_record/Battle_recordDTO.java, src/main/java/com/coma/app/biz/board/BoardDTO.java, src/main/java/com/coma/app/biz/common/SampleListener.java, src/main/java/com/coma/app/biz/crew/CrewDTO.java, src/main/java/com/coma/app/biz/crew_board/Crew_boardDTO.java, src/main/java/com/coma/app/biz/favorite/FavoriteDTO.java, src/main/java/com/coma/app/biz/grade/GradeDTO.java, src/main/java/com/coma/app/biz/gym/GymDTO.java, src/main/java/com/coma/app/biz/member/MemberDTO.java, src/main/java/com/coma/app/biz/product/ProductDTO.java, src/main/java/com/coma/app/biz/reply/ReplyDTO.java, src/main/java/com/coma/app/biz/reservation/ReservationDTO.java
=> [코드 수정] -종민 241027 VIEW

src/main/java/com/coma/app/biz/common/LogAdvice.java, src/main/java/com/coma/app/biz/common/PointcutCommon.java, src/main/java/com/coma/app/biz/favorite/FavoriteDAO.java, src/main/java/com/coma/app/biz/grade/GradeDAO.java, src/main/java/com/coma/app/biz/gym/GymDAO.java, src/main/java/com/coma/app/biz/gym/GymDTO.java, src/main/java/com/coma/app/biz/member/MemberDAO.java, src/main/java/com/coma/app/biz/member/MemberDTO.java, src/main/java/com/coma/app/biz/product/ProductDTO.java, src/main/java/com/coma/app/biz/reply/ReplyDAO.java, src/main/java/com/coma/app/biz/reservation/ReservationDAO.java, src/main/java/com/coma/app/biz/reservation/ReservationDTO.java
LogAdvice - AOP사용 로깅 코드 추가
PointcutCommon - AOP사용 로깅 코드 추가
DAO - AOP 사용으로 인한 로그 제거
DTO - 변수명 통일
=> [코드추가] - 선호 241027 DB

src/main/java/com/coma/app/biz/admin/MainManagementService.java, src/main/java/com/coma/app/biz/battle/BattleDTO.java, src/main/java/com/coma/app/biz/board/BoardDAO.java, src/main/java/com/coma/app/biz/board/BoardDTO.java, src/main/java/com/coma/app/biz/common/SampleListener.java, src/main/java/com/coma/app/biz/crew/CrewDAO.java, src/main/java/com/coma/app/biz/crew/CrewDTO.java, src/main/java/com/coma/app/biz/crew_board/Crew_boardDTO.java, src/main/java/com/coma/app/view/admin/BoardManagementController.java, src/main/java/com/coma/app/view/admin/MainManagementController.java, src/main/java/com/coma/app/view/admin/UserManagementController.java, src/main/java/com/coma/app/view/annotation/LoginCheck.java, src/main/java/com/coma/app/view/annotation/LoginCheckImpl.java, src/main/java/com/coma/app/view/asycnServlet/CKEditor_Upload.java, src/main/java/com/coma/app/view/asycnServlet/CrewBoardInsertAction.java, src/main/java/com/coma/app/view/asycnServlet/MailSend.java, src/main/java/com/coma/app/view/community/BoardUpdateController.java, src/main/java/com/coma/app/view/community/CommunityController.java, src/main/java/com/coma/app/view/crew/battle/CrewBattleOnePageController.java, src/main/java/com/coma/app/view/crew/common/CrewController.java, src/main/java/com/coma/app/view/crew/community/CrewCommunityPageController.java, src/main/java/com/coma/app/view/crew/join/CrewJoinPageController.java, src/main/java/com/coma/app/view/gym/GymController.java, src/main/java/com/coma/app/view/member/LoginAspect.java, src/main/java/com/coma/app/view/member/LoginController.java, src/main/java/com/coma/app/view/store/StoreController.java, src/main/resources/applicationContext.xml, src/main/webapp/WEB-INF/ds-servlet.xml
[로직 수정] - yena 241028 Controller
DTO - use_point, page, min_num 수정
ds-servlet.xml 수정
applicationContext.xml 수정
및 LoginCheck 어노테이션 관련 로직 수정
아직 안된 부분 (CKEditor )주석처리
및 중프인지 최프인지 확인안되는 코드 주석처리 했습니다
=> [로직 수정] - yena 241028 Controller

src/main/java/com/coma/app/biz/battle/BattleService.java, src/main/java/com/coma/app/biz/battle/BattleServiceImpl.java, src/main/java/com/coma/app/biz/board/BoardDAO.java, src/main/java/com/coma/app/biz/board/BoardService.java, src/main/java/com/coma/app/biz/board/BoardServiceImpl.java, src/main/java/com/coma/app/view/main/MainController.java, src/main/java/com/coma/app/view/main/MainPageController.java
boardDAO- 오타 수정 및 rowMapper return null 수정
=> [코드 수정] - 선아 20241028 

src/main/java/com/coma/app/biz/battle/BattleDTO.java, src/main/java/com/coma/app/biz/battle_record/Battle_recordDTO.java, src/main/java/com/coma/app/biz/board/BoardDAO.java, src/main/java/com/coma/app/biz/board/BoardDTO.java, src/main/java/com/coma/app/biz/crew/CrewDAO.java, src/main/java/com/coma/app/biz/crew/CrewDTO.java, src/main/java/com/coma/app/biz/crew_board/Crew_boardDAO.java, src/main/java/com/coma/app/biz/crew_board/Crew_boardDTO.java, src/main/java/com/coma/app/biz/gym/GymDAO.java, src/main/java/com/coma/app/biz/gym/GymDTO.java, src/main/java/com/coma/app/biz/gym/GymServiceImpl.java, src/main/java/com/coma/app/biz/member/MemberDAO.java, src/main/java/com/coma/app/biz/member/MemberDTO.java, src/main/java/com/coma/app/biz/reservation/ReservationDAO.java, src/main/java/com/coma/app/biz/reservation/ReservationDTO.java
DAO - 변수명 수정으로 인한 setter 메서드명 변경
DTO - 변수명 수정
=> [코드변경] - 선호 241028 DB

src/main/java/com/coma/app/view/community/BoardController.java, src/main/java/com/coma/app/view/community/CommunityController.java, src/main/java/com/coma/app/view/community/ReplyController.java, src/main/java/com/coma/app/view/crew/battle/CrewBattleController.java, src/main/java/com/coma/app/view/crew/common/CrewController.java, src/main/java/com/coma/app/view/main/MainController.java, src/main/webapp/WEB-INF/views/join.jsp
BoardController.java, CommunityController.java, CrewBattleController.java, CrewController.java, join.jsp, MainController.java, ReplyController.java
=> [로직 수정] - junyeol 241028 Controller

src/main/java/com/coma/app/biz/battle/BattleDAO.java, src/main/java/com/coma/app/biz/battle/BattleService.java, src/main/java/com/coma/app/biz/battle/BattleServiceImpl.java, src/main/java/com/coma/app/biz/battle_record/Battle_recordDAO.java, src/main/java/com/coma/app/biz/board/BoardDAO.java, src/main/java/com/coma/app/biz/board/BoardService.java, src/main/java/com/coma/app/biz/board/BoardServiceImpl.java, src/main/java/com/coma/app/biz/crew/CrewDAO.java
BoardDAO, BattleDAO, Battle_recordDAO, CrewDAO- 쿼리문 확인 및 수정
=> [코드 수정] - 선아 20241028

pom.xml, src/main/java/com/coma/app/view/asycnServlet/CKEditor_Upload.java, src/main/java/com/coma/app/view/asycnServlet/CKEditor_Upload2.java, src/main/java/com/coma/app/view/asycnServlet/FTPService.java, src/main/resources/applicationContext.xml
pom.xml [commons-net] 의존 추가
CKEditor_Upload.java :
FTPServer Upload 추가
FTPService.java : 로직추가
applicationContext.xml
FTP 서버를 클래스 Bean 을 추가
=> [로직수정] - 상도 241028

src/main/java/com/coma/app/biz/gym/GymDAO.java, src/main/java/com/coma/app/biz/reservation/ReservationDTO.java
GymDAO,ReservationDTO - ResultSet 컬럼명 수정 , string->int
=> [코드 수정] - 선아 20241029

src/main/webapp/WEB-INF/admin/main.jsp, src/main/webapp/WEB-INF/tags/gnb.tag
gnb.tag URL 변경 :
MAINPAGEACTION.do -> main.do 수정
main.jsp EL식 추가
Line Number
142, 187, 195, 203
=> [로직수정] - 상도 241029 VIEW

src/main/java/com/coma/app/view/admin/ReservationManagementController.java, src/main/java/com/coma/app/view/community/CommunityController.java, src/main/java/com/coma/app/view/community/ReplyController.java
ReservationManagementController.java, ReplyController.java, ReservationManagementController.java
=> [로직 수정] - junyeol 241029 Controller

src/main/java/com/coma/app/biz/gym/GymDAO.java, src/main/java/com/coma/app/view/admin/ReservationManagementController.java, src/main/java/com/coma/app/view/gym/GymController.java, src/main/resources/applicationContext.xml
GymController.java - 메서드 수정
GymDAO - CRUD수정
ReservationManagementController.java - 메서드 수정
=> [코드변경] - 선호 241029 DB

src/main/java/com/coma/app/view/asycnServlet/FTPService.java, src/main/java/com/coma/app/view/function/SMSPush.java, src/main/webapp/WEB-INF/views/crewList.jsp, src/main/webapp/WEB-INF/views/editMyPage.jsp, src/main/webapp/WEB-INF/views/gymMain.jsp, src/main/webapp/WEB-INF/views/join.jsp
=> [로직수정] - 상도 241029

src/main/java/com/coma/app/biz/board/BoardDAO.java, src/main/java/com/coma/app/view/community/CommunityController.java
CommunityController.java, GymManagementController.java - 커뮤니티 수정
=> [로직수정] junyeol 241029 controller

src/main/java/com/coma/app/biz/board/BoardDAO.java
BoardDAO - getPage() -> getBoard_min_num() / writer_id -> board_content
=> [코드 수정] - 선아 20241029 

src/main/java/com/coma/app/view/admin/GymManagementController.java, src/main/java/com/coma/app/view/admin/ReservationManagementController.java, src/main/java/com/coma/app/view/community/BoardController.java, src/main/webapp/WEB-INF/admin/gymManagement.jsp
BoardController.java, GymManagementController.java, gymManagement.jsp, ReservationManagementController.java  - 수정
=> [로직수정] junyeol 241030 controller

src/main/java/com/coma/app/view/asycnServlet/FTPService.java, src/main/webapp/WEB-INF/views/communityRegions.jsp, src/main/webapp/WEB-INF/views/editMyPage.jsp, src/main/webapp/WEB-INF/views/localCommunity.jsp
FTPService.java 메서드 추가
localCommunity.jsp 페이지네이션 변경
editMyPage.jsp ajax pwCheck url 변경
communityRegions.jsp 검색 search_keyword 로 수정
=> [로직수정] - 상도 241030

src/main/java/com/coma/app/biz/gym/GymDTO.java, src/main/java/com/coma/app/biz/reservation/ReservationDAO.java
GymDTO - 변수명 추가 MultipartFile gym_file
이미지 업로드시 사용하는 변수
ReservationDAO - 쿼리문 추가 selectOneCountAdmin 전체 예약 개수 출력
=> [코드추가] - 선호 241030 DB

src/main/java/com/coma/app/view/admin/BoardManagementController.java, src/main/java/com/coma/app/view/admin/CrewAsyncController.java, src/main/java/com/coma/app/view/admin/ReservationManagementController.java
[코드 수정] - yena 241030 Controller
관리자 Controller 수정
=> [코드 수정] - yena 241030 Controller

src/main/java/com/coma/app/biz/admin/MainManagementService.java, src/main/java/com/coma/app/biz/member/MemberDAO.java, src/main/java/com/coma/app/biz/member/MemberServiceImpl.java, src/main/java/com/coma/app/view/admin/MainManagementController.java, src/main/java/com/coma/app/view/admin/UserManagementController.java, src/main/webapp/WEB-INF/admin/crewManagement.jsp, src/main/webapp/WEB-INF/admin/crewManagementDetail.jsp, src/main/webapp/WEB-INF/admin/main.jsp, src/main/webapp/WEB-INF/admin/userManagement.jsp, src/main/webapp/WEB-INF/admin/userManagementDetail.jsp, src/main/webapp/WEB-INF/tags/admin_gnb.tag, src/main/webapp/WEB-INF/views/info.jsp, src/main/webapp/js/sweetAlert_modal.js
admin_gnb.tag :
url 수정 && 로그아웃 기능 추가
crewManagement.jsp :
url 수정
crewManagementDetail.jsp :
게시글 불러오는 과정 EL 수정
userManagement.jsp :
삭제 기능 오류 수정
userManagementDetail.jsp :
등록버튼 SweetAlert 추가
info.jsp
info 페이지 이동 후 확인 클릭 없이
페이지 전환되던 오류 수정
main.jsp
Chart js 문제 해결 및 EL 변수명 수정
sweetAlert_modal.js
공백 문제 전달시 실행되지 않던 오류 해결
MainManagementController.java
Chart js를 위해 ObjectMapping 추가
MainManagementService.java
공백문자로 인한 JSON 파싱 오류 해결
MemberDAO.java
관리자 수정관련 쿼리문 변경
ID를 제외한 모든 정보 수정
UPDATE MEMBER SET MEMBER_PASSWORD = ?,
MEMBER_NAME = ?,
MEMBER_CURRENT_POINT = ?,
MEMBER_LOCATION = ?,
MEMBER_CREW_NUM = ?,
MEMBER_PHONE = ?,
MEMBER_ROLE = ?
WHERE MEMBER_ID = ?
MemberServiceImpl.java
NPE 오류를 방지하기 위해
null 유효성 검사 추가
UserManagementController.java
정보수정 페이지 로직 수정
회원추가로직 -> 회원수정로직
전달 url 오류로 페이지 이동 불가 오류 해결
=> [로직 수정] 상도 20241031 02:04

src/main/java/com/coma/app/biz/gym/GymDAO.java, src/main/java/com/coma/app/biz/gym/GymService.java, src/main/java/com/coma/app/biz/gym/GymServiceImpl.java, src/main/java/com/coma/app/biz/member/MemberDAO.java, src/main/java/com/coma/app/biz/member/MemberService.java, src/main/java/com/coma/app/biz/member/MemberServiceImpl.java, src/main/java/com/coma/app/biz/reservation/ReservationDAO.java, src/main/java/com/coma/app/biz/reservation/ReservationService.java, src/main/java/com/coma/app/biz/reservation/ReservationServiceImpl.java
GymDAO - 카운트 메서드 추가,
전체 암벽장 이름검색 메서드 추가
selectOneAdminSearchCount - 전체 암벽장 중 이름 검색 카운트
selectOneAdminVerifiedCount - 승인,비승인된 암벽장 중 이름 검색 카운트
selectAllAdminSearch - 전체 암벽장 중 이름 검색
ReservationDAO - 카운트 메서드 추가 
selectOneCountSearchGymNameAdmin - 암벽장 이름으로 검색한 예약 전체 카운트
selectOneCountSearchMemberIdAdmin - 예약자 이름으로 검색한 예약 전체 카운트
MemberDAO - 카운트 메서드 추가
selectOneSearchCountAdmin - 회원 검색 카운트
selectOneSearchIdCountAdmin - 회원 아이디로 검색 카운트
selectOneSearchDateCountAdmin - 회원 가입날짜로 검색 카운트
=> [코드추가 및 수정]선호 241031 DB

src/main/java/com/coma/app/biz/admin/CrewManagementService.java, src/main/java/com/coma/app/biz/battle/BattleDAO.java, src/main/java/com/coma/app/biz/crew/CrewDAO.java, src/main/java/com/coma/app/view/admin/CrewAsyncController.java, src/main/java/com/coma/app/view/admin/CrewManagementController.java, src/main/webapp/WEB-INF/admin/crewManagement.jsp, src/main/webapp/WEB-INF/admin/crewManagementDetail.jsp, src/main/webapp/js/crewManagementAjax.js
BattleDAO.java
CrewAsyncController.java
CrewDAO.java
crewManagement.jsp
crewManagementAjax.js
CrewManagementController.java
crewManagementDetail.jsp
CrewManagementService.java
crewManagementDetail.jsp ( 미완성 )
crewManagementAjax.js ( 확인 필요 )
=> [코드 수정] - 김종민 241031 VIEW

src/main/java/com/coma/app/biz/admin/CrewManagementService.java, src/main/java/com/coma/app/biz/battle/BattleDAO.java, src/main/java/com/coma/app/biz/gym/GymDAO.java, src/main/java/com/coma/app/biz/gym/GymServiceImpl.java, src/main/java/com/coma/app/view/admin/BoardManagementController.java, src/main/java/com/coma/app/view/admin/CrewAsyncController.java, src/main/java/com/coma/app/view/admin/CrewManagementController.java, src/main/java/com/coma/app/view/admin/GymManagementController.java, src/main/java/com/coma/app/view/member/CheckController.java, src/main/webapp/WEB-INF/admin/crewManagement.jsp, src/main/webapp/WEB-INF/admin/gymManagement.jsp, src/main/webapp/WEB-INF/admin/main.jsp, src/main/webapp/WEB-INF/admin/userManagement.jsp, src/main/webapp/WEB-INF/tags/admin_gnb.tag, src/main/webapp/js/crewManagementAjax.js, src/main/webapp/js/datepicker.js
=> [로직 수정] 상도 20241031 오후 19:44

src/main/java/com/coma/app/biz/admin/CrewManagementService.java, src/main/java/com/coma/app/biz/battle_record/Battle_recordDAO.java, src/main/java/com/coma/app/view/admin/CrewManagementController.java, src/main/webapp/WEB-INF/admin/crewManagement.jsp
=> [로직 수정] 상도 20241031 오후 20:43

src/main/java/com/coma/app/biz/battle/BattleDAO.java
BattleDAO.java ALL_SEARCH_PARTICIPANTS
쿼리 수정
=> [로직 수정] 상도 20241031 오후 21:29

src/main/java/com/coma/app/view/crew/community/CrewCommunityPageController.java, src/main/java/com/coma/app/view/crew/community/CrewCommunityWebSocket.java, src/main/webapp/WEB-INF/views/crewCommunity.jsp
=> [로직 구성] - 김종민 241101 VIEW

pom.xml, src/main/java/com/coma/app/biz/common/Crawling2.java
Crawling2.java
스피릿 사이트 광고 삭제
pom.xml
의존성 추가
<dependency>
<groupId>jakarta.websocket</groupId>
<artifactId>jakarta.websocket-api</artifactId>
</dependency>
=> [로직 수정] 상도 20241101 오전 10:07

src/main/java/com/coma/app/biz/member/MemberDAO.java, src/main/java/com/coma/app/biz/member/MemberService.java, src/main/java/com/coma/app/biz/member/MemberServiceImpl.java, src/main/java/com/coma/app/view/asycnServlet/MailSend.java, src/main/java/com/coma/app/view/function/GoogleAuthentication.java, src/main/java/com/coma/app/view/member/CheckController.java, src/main/webapp/WEB-INF/views/login.jsp, src/main/webapp/js/checkEmail.js
MemberDAO.java, MemberService.java, MemberServiceImpl.java, MailSend.java, GoogleAuthentication.java, CheckController.java, checkEmail.js, login.jsp 이메일API구현 완료
=> [로직수정] junyeol 2411101 controller

src/main/java/com/coma/app/view/member/LoginController.java
[코드 수정] - yena 241101 Controller
로그인체크 수정
=> [코드 수정] - yena 241101 Controller

src/main/java/com/coma/app/biz/member/MemberDTO.java, src/main/java/com/coma/app/view/asycnServlet/FTPService.java, src/main/java/com/coma/app/view/mypage/MyPageController.java
FTPService.java
로직 추가
MemberDTO.java
Member FTP Server 추가
MyPageController.java
Member FTP Server 추가
=> [로직 수정] 상도 20241101 오후 20:11

src/main/java/com/coma/app/view/mypage/MyPageController.java, src/main/webapp/WEB-INF/views/editMyPage.jsp
FTPService.java
로직 추가
MyPageController.java
FTP Server 추가
editMyPage.jsp
mypage.jsp -> myPage.jsp 수정
=> [로직 수정] 상도 20241101 오후 21:40

src/main/java/com/coma/app/view/gym/CrewBattleApplicationController.java, src/main/webapp/WEB-INF/views/gymInformation.jsp, src/main/webapp/payment.jsp
CrewBattleApplicationController - 유효성검사 추가 및 코드 수정
=> [코드수정]선호 241102 DB

src/main/java/com/coma/app/view/admin/AdminAspect.java, src/main/java/com/coma/app/view/admin/MainManagementController.java, src/main/java/com/coma/app/view/annotation/AdminCheck.java, src/main/java/com/coma/app/view/annotation/AdminCheckImpl.java, src/main/java/com/coma/app/view/annotation/LoginCheckImpl.java, src/main/java/com/coma/app/view/crew/common/CrewController.java, src/main/java/com/coma/app/view/member/LoginAspect.java, src/main/java/com/coma/app/view/member/LoginController.java, src/main/webapp/WEB-INF/views/login.jsp
[코드 수정 및 로직 추가] - yena 241103 Controller
@AdminCheck 어노테이션 추가 및 로직 추가
유효성 검사 빡빡하게 하기 ..
=> [코드 수정 및 로직 추가] - yena 241103 Controller

src/main/java/com/coma/app/biz/crew_board/Crew_boardDAO.java, src/main/java/com/coma/app/biz/crew_board/Crew_boardDTO.java, src/main/java/com/coma/app/biz/crew_board/Crew_boardService.java, src/main/java/com/coma/app/view/crew/community/CrewCommunityPageController.java, src/main/java/com/coma/app/view/crew/community/CrewCommunityWebSocket.java, src/main/resources/applicationContext.xml, src/main/webapp/WEB-INF/views/crewCommunity.jsp
Crew_boardDAO.java
crewCommunity.jsp
CrewCommunityWebSocket.java
첫 채팅방 진입시 최근 10개 게시글 출력
applicationContext.xml - crew_boardService 트랜잭션 설정
Crew_boardDAO.java
Crew_boardDTO.java
Crew_boardService.java
CrewCommunityPageController.java
CrewCommunityWebSocket.java
=> [로직 수정] 김종민 241104 VIEW

src/main/webapp/WEB-INF/views/communityRegions.jsp, src/main/webapp/WEB-INF/views/content.jsp, src/main/webapp/WEB-INF/views/crewBattleContent.jsp, src/main/webapp/WEB-INF/views/crewBattleMain.jsp, src/main/webapp/WEB-INF/views/crewRank.jsp, src/main/webapp/WEB-INF/views/editMyPage.jsp, src/main/webapp/WEB-INF/views/gymInformation.jsp, src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/myCrewPage.jsp, src/main/webapp/WEB-INF/views/personalRank.jsp, src/main/webapp/error/404error.jsp, src/main/webapp/error/500error.jsp
404error.jsp
500error.jsp
communityRegions.jsp
content.jsp
crewBattleContent.jsp
crewBattleMain.jsp
crewRank.jsp
editMyPage.jsp
gymInformation.jsp
main.jsp
myCrewPage.jsp
personalRank.jsp
FTPServer cdn 주소 추가.
=> [로직 수정] 상도 20241105 오후 12:55

src/main/java/com/coma/app/biz/battle/BattleDAO.java, src/main/java/com/coma/app/biz/battle/BattleService.java, src/main/java/com/coma/app/biz/battle/BattleServiceImpl.java, src/main/java/com/coma/app/view/admin/GymManagementController.java, src/main/java/com/coma/app/view/gym/CrewBattleApplicationController.java, src/main/webapp/WEB-INF/views/gymInformation.jsp
BattleDAO.java - 쿼리문 수정, 추가(크루전 개최 및 등록)
BattleService.java - 쿼리문 추가
BattleServiceImpl.java - 쿼리문 추가
(추가한 쿼리문 : selectOneSearchBattleAdmin, insertFirst)
GymManagementController.java - 크루전 개최 및 등록 로직 수정 (진행중) CrewBattleApplicationController.java - 크루전 개최 및 등록 로직 수정 gymInformation.jsp - 변수명 및 액션명 통일
=> [코드추가 및 수정]선호 241106 DB

src/main/java/com/coma/app/biz/member/MemberDAO3.java, src/main/webapp/WEB-INF/views/login.jsp
임시비밀번호 전송 버튼 수정 및 MemberDAO3 수정
=> [로직수정] junyeol 2411106 controller

src/main/java/com/coma/app/view/admin/BoardManagementController.java, src/main/java/com/coma/app/view/admin/CrewAsyncController.java, src/main/java/com/coma/app/view/admin/CrewManagementController.java, src/main/java/com/coma/app/view/admin/GymManagementController.java, src/main/java/com/coma/app/view/admin/MainManagementController.java, src/main/java/com/coma/app/view/admin/ReservationManagementController.java, src/main/java/com/coma/app/view/admin/UserManagementController.java, src/main/java/com/coma/app/view/annotation/AdminCheckService.java, src/main/java/com/coma/app/view/annotation/CrewCheckService.java, src/main/java/com/coma/app/view/annotation/LoginCheckService.java
[주석 수정] - yena 241106 Controller
=> [주석 수정] - yena 241106 Controller

src/main/webapp/WEB-INF/views/crewRank.jsp, src/main/webapp/WEB-INF/views/grigri.jsp, src/main/webapp/WEB-INF/views/personalRank.jsp
crewRank,personalRank - 주소 추가
grigri - / 삭제
=> [코드 수정] - 선아 20241106

src/main/webapp/WEB-INF/admin/gymManagement.jsp, src/main/webapp/WEB-INF/admin/main.jsp, src/main/webapp/WEB-INF/views/crewBattleMain.jsp
gymManagement.jsp
main.jsp
crewBattleMain.jsp
FTP Server 주소 추가
=> [로직 수정] 상도 20241106 오후 16:59
